### ISSUE TITLE
Для проверки Docker-инструкции следует использовать следующий скрипт

### ISSUE THREAD

**Issue by Kerminator1973** [Kerminator1973/WebDevelopment#4]
```sql
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "Surname" text,
    "IsUserActive" boolean NOT NULL,
    "WhyIsUserBlocked" text,
    "IsUserDeleted" boolean NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AuditEvents" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "EventID" integer NOT NULL,
    "DateTime" timestamp without time zone NOT NULL,
    "UserId" text,
    "StorageID" integer NOT NULL,
    "ModuleNumber" integer NOT NULL,
    "CellNumber" integer NOT NULL,
    "Message" text,
    CONSTRAINT "PK_AuditEvents" PRIMARY KEY ("ID")
);

CREATE TABLE "ModuleLinkers" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "StorageID" integer NOT NULL,
    "LogicalNumber" integer NOT NULL,
    "CenterX" integer NOT NULL,
    "CenterY" integer NOT NULL,
    CONSTRAINT "PK_ModuleLinkers" PRIMARY KEY ("ID")
);

CREATE TABLE "Storages" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(80) NOT NULL,
    "IPAddr" character varying(40) NOT NULL,
    "City" character varying(40) NOT NULL,
    "PostAddr" character varying(200) NOT NULL,
    "PublicKey" text,
    "ModuleLinkerHeight" integer NOT NULL,
    "StorageContentType" character varying(40),
    "StorageImage" bytea,
    CONSTRAINT "PK_Storages" PRIMARY KEY ("ID")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE UNIQUE INDEX "UniqueStorage_LogicalNumber" ON "ModuleLinkers" ("StorageID", "LogicalNumber");

CREATE UNIQUE INDEX "IX_Storages_IPAddr" ON "Storages" ("IPAddr");

CREATE UNIQUE INDEX "IX_Storages_Name" ON "Storages" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240412055733_FirstMigration', '8.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "Storages" DROP COLUMN "PublicKey";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240521085851_RemovedCerticiate', '8.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "ModuleLinkers" ADD "FirstSafeInModule" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240715130856_FirstSafeInModule', '8.0.4');

COMMIT;

START TRANSACTION;

CREATE TABLE "CriticalIssues" (
    "ID" uuid NOT NULL,
    "StorageID" integer NOT NULL,
    "ModuleNumber" integer NOT NULL,
    "CellNumber" integer NOT NULL,
    "Message" character varying(255) NOT NULL,
    "HasProcessed" boolean NOT NULL,
    CONSTRAINT "PK_CriticalIssues" PRIMARY KEY ("ID")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240819145226_CriticalIssues', '8.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "CriticalIssues" ADD "DateTime" timestamp without time zone NOT NULL DEFAULT TIMESTAMP '-infinity';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240820094355_CriticalIssueDateTime', '8.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "CriticalIssues" DROP COLUMN "HasProcessed";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240820124943_RemovedHasProcessed', '8.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "AuditEvents" ADD "Level" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240912112057_AddMessageLevel', '8.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "Storages" ADD "LastKnownStatus" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240926130350_LastKnownStatus', '8.0.4');

COMMIT;
```

**Comment by Kerminator1973** [comment]
1 warning found (use docker --debug to expand):
 - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ENV "POSTGRES_PASSWORD") (line 7)

**Comment by Kerminator1973** [comment]
Собранный CinnaPages.runtimeconfig.json:

```
{
  "runtimeOptions": {
    "tfm": "net8.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "8.0.110"
    },
    "rollForward": "latestMinor"
  }
}
```

Падает с сообщением:

```
Unhandled exception. System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.ApplicationParts.ConsolidatedAssemblyApplicationPartFactory' from assembly 'Microsoft.AspNetCore.Mvc.Razor, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Reflection.RuntimeAssembly.GetTypeCore(String, ReadOnlySpan`1, Boolean, Boolean)
   at System.Reflection.TypeNameParser.GetType(String, ReadOnlySpan`1, String)
   at System.Reflection.TypeNameParser.NamespaceTypeName.ResolveType(TypeNameParser&, String)
   at System.Reflection.TypeNameParser.Parse()
   at System.Reflection.TypeNameParser.GetType(String, Func`2, Func`4, Assembly, Boolean , Boolean , Boolean )
   at System.Reflection.TypeNameParser.GetType(String, Assembly, Boolean , Boolean )
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ProvideApplicationPartFactoryAttribute.GetFactoryType()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartFactory.GetApplicationPartFactory(Assembly)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateDefaultParts(String)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection, IWebHostEnvironment)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersCore(IServiceCollection)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllers(IServiceCollection)
   at Program.<Main>$(String[]) in /home/developer/projects/ProIDC3/source/CinnaPages/Program.cs:line 84
   at Program.<Main>(String[])
Aborted (core dumped)
```

**Comment by Kerminator1973** [comment]
Данные перенесены в Mantis.
